export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCT = 'SET_PRODUCT';
export const SET_INITIAL_PRODUCTS = 'SET_INITIAL_PRODUCTS';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SET_CHART = 'SET_CHART';
export const SET_LOADING = 'SET_LOADING';
export const SET_SUGGESTIONS = 'SET_SUGGESTIONS';